name: "Greg Major's Blog"
description: ""

url: "http://blog.gregmajor.com"
#url: "localhost"

paginate: 4
paginate_path: "page:num"

markdown: rdiscount
permalink: pretty
highlighter: pygments

syntax-highlighting:
  enabled : true
  css: syntax.css
